# This the theme configuration.
# Allowed configuration in a theme is (currently):
# params (global and per language)
# menu (global and per language)
# outputformats and mediatypes


[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "2006-01-02"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]

